[build]
  command = "pip install -r requirements.txt && mkdir -p .streamlit && echo '[server]\nheadless = true\nport = $PORT\nenableCORS = false\n' > .streamlit/config.toml"
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/"
  status = 200