[build]
  command = "pip install --upgrade pip && pip install wheel && pip install -r requirements.txt && mkdir -p .streamlit && echo '[server]\nheadless = true\nport = $PORT\nenableCORS = false\n' > .streamlit/config.toml"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"